the factory must grow the factory must grow the factory must grow the…
3kh0/3kh0-lite pull request #15
Opened 2024-08-14 02:56 UTC by silvereengames

the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow the factory must grow

2024-08-16 01:35 UTC, HankMH commented
what

2024-08-16 04:41 UTC, 3kh0 commented on js/subtitle.js
> +    "<h1>E</h1>",
please do not xss

2024-08-16 04:41 UTC, 3kh0 commented on misc.html
> +        <h1><a href="javascript:alert('Easter egg placed by yours truely. \n -Silvereen 🥚')" style="text-decoration: none; color: white;">T</a>ab Cloaker</h1>
not needed

2024-08-16 04:43 UTC, 3kh0 requested changes
Please see comments attached

2024-08-16 04:43 UTC, 3kh0 commented on projects.html
what is actually being changed here? it seems only that spacing is being modified

2024-08-17 17:51 UTC, HankMH commented on projects.html
dude im just trying to get games for school what does this mean

2024-08-30 21:32 UTC, silvereengames commented on js/subtitle.js
> +    "<h1>E</h1>",
pls do

2024-08-30 21:32 UTC, silvereengames commented on misc.html
> +        <h1><a href="javascript:alert('Easter egg placed by yours truely. \n -Silvereen 🥚')" style="text-decoration: none; color: white;">T</a>ab Cloaker</h1>
yes it is...

2024-08-30 21:33 UTC, silvereengames commented on projects.html
i dont fucking know merge the pr already

2024-08-31 03:39 UTC, 3kh0 commented
no

2024-08-31 03:39 UTC, closed without merging